### ISSUE TITLE
Report Python info both in and out of the tox env in GitHub Actions

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10129]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)| @altendky reported|
|-|-|
|Trac ID|trac#10129|
|Type|enhancement|
|Created|2021-03-14 00:42:06Z|

<details><summary>Searchable metadata</summary>

```
trac-id__10129 10129
type__enhancement enhancement
reporter__altendky altendky
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1615682526288010 1615682526288010
changetime__1615682526288010 1615682526288010
version__None None
owner__None None
cc__altendky
```
</details>

**Comment by adiroiban** [comment]
@altendky what needs to be done here.

We now have `twisted/python-info-action@v1` to report the general python version.

and then we also have python version and deps inside tox https://github.com/twisted/twisted/runs/8058083123?check_suite_focus=true#step:10:35

```
alldeps-withcov-posix run-test: commands[0] | python /home/runner/work/twisted/twisted/admin/dump_all_version_info.py
Python info
  /home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix
  /home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix
  /home/runner/work/twisted/twisted/.tox/alldeps-withcov-posix/bin/python
  3.9.13 (main, Jul 22 2022, 09:23:[34](https://github.com/twisted/twisted/runs/8058083123?check_suite_focus=true#step:10:35)) 
  [GCC 9.4.0]
  linux
> Deps info
  INFO REMOVED
alldeps-withcov-posix run-test: commands[1] | python -c 'print('"'"'Running on POSIX (no special dependencies)'"'"')'
Running on POSIX (no special dependencies)
```

can this be closed?

**Comment by altendky** [comment]
So the remaining piece, if you want it, is to report the full info from the tox env as well.  There are a couple options.  You can do a tox build-only step, report, then run tox using the already built env.  If you want that I can dig up an example somewhere, I forget.  I guess it could also be added as a step after a regular tox run with `if: always()`.  Either way, you would pass the env path to the action.  I guess that would depend on the tox environment name if the path isn't overridden.

Here's the fancy form.

https://github.com/twisted/python-info-action/blob/bd67248a4c43998146eed53471363f5963cdc2b9/.github/workflows/ci.yml#L128-L150
```yaml
    - name: Create tox env with build installed
      shell: bash
      run: |
        python -m pip install tox
        python -m tox -c tox_example.ini --notest -e with_build
    - name: Run the action for the tox env
      uses: ./
      env:
        A_SECRET: '<masked>'
      with:
        output-path: output_tox.log
        python-path: .tox/with_build/*/python

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os.name }} - ${{ matrix.python.name }}
        path: output_tox.log

    - name: Test - tox
      shell: bash
      run: |
        python test.py --path output_tox.log --package build 0.3.1 --sys-prefix "$(.tox/with_build/*/python -c 'import sys; sys.stdout.write(sys.prefix)')"
```

Close if you like, or opine on what form you'd like and I can help or presumably just do it.
