### ISSUE TITLE
Run major dependencies' test suites as part of CI (or perhaps just release process?)

### ISSUE THREAD

**Issue by itamarst** [twisted/twisted#12348]
While it is not feasible to run tests for all projects that depend on Twisted, Twisted does have a few major projects that rely on it that are widely used, and breaking them would be unfortunate. Running their test suites in CI would reduce the chances of breakage. Obvious packages include:

* Scrapy: responsible for 20% of Twisted's downloads from PyPI.
* Daphne: responsible for another 20% of Twisted's downloads from PyPI.
* Treq: 5% maybe.
* ... what other packages?

This could be every PR, or e.g. an overnight run.

**Comment by adiroiban** [comment]
I don't know if we have the "energy" to look after all these projects.

We are already fighing to keep the current Twisted tests passing on Linux, Windows and macOS ... with macOS tests not yet fixed and still generating random failures.

------

For `treq` there is already a job to run the `treq` test suite using lowest and latest Twisted release


I guess that it can be updated to also run the tests using Twisted trunk.

```
  test:
    name: "Test ${{ matrix.python-version }} with ${{ matrix.twisted-version }} Twisted"
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
          # Python versions common to lowest and latest
          python-version: ["3.8", "3.9", "3.10", "pypy-3.9"]
          twisted-version: ["lowest", "latest"]
```

https://github.com/twisted/treq/blob/132fd9c652da3d02774b8fe723bc81c52d3137a6/.github/workflows/ci.yaml#L61-L70


-----------

My guess is that if there as a test failure, for the `treq` or `daphne` development team it will be easier to tell if the failure is due to Twisted or due to a failure in the downstream project.
